---
title: "DevOps Process Explanatory Data Analysis"
author: "János Poór"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
---


```{r knitr_init, echo=FALSE, cache=FALSE, message=FALSE, warning=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r, message=FALSE, warning=FALSE}
library(here)
library(dplyr)
library(ggplot2)
library(lubridate)
library(scales)
library(tidyr)
```

```{r, message=FALSE, include=FALSE}
#########################################################################################
# Data Extraction #######################################################################
#########################################################################################

# Set JAVA_HOME, set max. memory, and load rJava library
Sys.setenv(JAVA_HOME = "C:\\Program Files\\Java\\jre1.8.0_171")
options(java.parameters = "-Xmx2g")
library(rJava)

# Output Java version
.jinit()
print(.jcall("java/lang/System", "S", "getProperty", "java.version"))

# Load RJDBC library
library(RJDBC)

# Get credentials
datamnr <-
  config::get("datamnr", file = "C:\\Users\\PoorJ\\Projects\\config.yml")

# Create connection driver
jdbcDriver <-
  JDBC(driverClass = "oracle.jdbc.OracleDriver", classPath = "C:\\Users\\PoorJ\\Desktop\\ojdbc7.jar")

# Open connection: kontakt---------------------------------------------------------------
jdbcConnection <-
  dbConnect(
    jdbcDriver,
    url = datamnr$server,
    user = datamnr$uid,
    password = datamnr$pwd
  )


# Get SQL scripts
readQuery <-
  function(file)
    paste(readLines(file, warn = FALSE), collapse = "\n")

# Fetch data
query_isd <- readQuery(here::here("SQL", "get_ISD_data.sql"))
t_isd <- dbGetQuery(jdbcConnection, query_isd)

# Close db connection: kontakt
dbDisconnect(jdbcConnection)


# Transformations
t_isd <- t_isd %>% mutate(CREATED = ymd_hms(CREATED),
                          TIMESTAMP = ymd_hms(TIMESTAMP))
```


# Number of Tickets Started and Closed
```{r, fig.width=12}
t_started <- t_isd %>%
  # Transform data
  filter(TIMESTAMP >= as.Date("2017-06-01") & TIMESTAMP <= as.Date("2019-05-31")) %>%
  mutate(EVENT_MONTH = floor_date(TIMESTAMP, unit = "month")) %>%
  group_by(CASE, CLASSIFICATION) %>%
  summarize(MONTH = min(EVENT_MONTH)) %>%
  ungroup() %>%
  group_by(MONTH, CLASSIFICATION) %>%
  summarize(STARTED = n()) %>%
  ungroup()

t_closed <- t_isd %>%
  # Transform data
  filter(TIMESTAMP >= as.Date("2017-06-01") & TIMESTAMP <= as.Date("2019-05-31")) %>%
  mutate(EVENT_MONTH = floor_date(TIMESTAMP, unit = "month")) %>%
  group_by(CASE, CLASSIFICATION) %>%
  summarize(MONTH = max(EVENT_MONTH)) %>%
  ungroup() %>%
  group_by(MONTH, CLASSIFICATION) %>%
  summarize(CLOSED = n()) %>%
  ungroup()

t_started %>% left_join(t_closed, by = c("MONTH", "CLASSIFICATION")) %>%
  tidyr::gather(-MONTH, -CLASSIFICATION, key = METRIC, value = COUNT) %>% 
  tidyr::replace_na(list(COUNT = 0)) %>% 
  # Plot
  ggplot(aes(x = substr(as.character(MONTH), 1, 7), y = COUNT, group = METRIC, colour = METRIC)) +
  geom_line(size = 0.8) +
  #scale_y_continuous(label = unit_format(unit = "K", scale = 1e-3)) +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_grid(.~CLASSIFICATION, labeller = label_wrap_gen(width = 10)) +
  labs(
    x = "Month",
    y = "# of Tickets",
    title = "Number of Tickets Started and Closed"
  )
```


# Number of Tickets Started and Closed by Application Group
```{r, fig.width=12}
t_started <- t_isd %>%
  # Transform data
  filter(TIMESTAMP >= as.Date("2017-06-01") & TIMESTAMP <= as.Date("2019-05-31")) %>%
  mutate(EVENT_MONTH = floor_date(TIMESTAMP, unit = "month")) %>%
  group_by(CASE, CLASSIFICATION, APPGROUP) %>%
  summarize(MONTH = min(EVENT_MONTH)) %>%
  ungroup() %>%
  group_by(MONTH, CLASSIFICATION, APPGROUP) %>%
  summarize(STARTED = n()) %>%
  ungroup()

t_closed <- t_isd %>%
  # Transform data
  filter(TIMESTAMP >= as.Date("2017-06-01") & TIMESTAMP <= as.Date("2019-05-31")) %>%
  mutate(EVENT_MONTH = floor_date(TIMESTAMP, unit = "month")) %>%
  group_by(CASE, CLASSIFICATION, APPGROUP) %>%
  summarize(MONTH = max(EVENT_MONTH)) %>%
  ungroup() %>%
  group_by(MONTH, CLASSIFICATION, APPGROUP) %>%
  summarize(CLOSED = n()) %>%
  ungroup()

t_started %>% left_join(t_closed, by = c("MONTH", "CLASSIFICATION", "APPGROUP")) %>%
  tidyr::gather(-MONTH, -CLASSIFICATION, -APPGROUP, key = METRIC, value = COUNT) %>% 
  tidyr::replace_na(list(COUNT = 0)) %>% 
  # Plot
  ggplot(aes(x = substr(as.character(MONTH), 1, 7), y = COUNT, group = METRIC, colour = METRIC)) +
  geom_line(size = 0.8) +
  #scale_y_continuous(label = unit_format(unit = "K", scale = 1e-3)) +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_grid(APPGROUP~CLASSIFICATION, labeller = label_wrap_gen(width = 10)) +
  labs(
    x = "Month",
    y = "# of Tickets",
    title = "Number of Tickets Started and Closed"
  )
```